name: learning-aws

services:

  app:
    build: .
    container_name: hello-learning-aws

    ports:
      - "3000:3000"

    env_file:
      - .env

    depends_on:
      - postgres

  postgres:
    image: postgres:17

    container_name: postgres

    environment:
      POSTGRES_DB: nodejs_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hoangth89

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: