name: Node CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install packages
        run: npm install

      - name: Debug GitHub context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Ref name: ${{ github.ref_name }}"

      # GitHub OIDC → AWS IAM Role
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::749203477175:role/GitHubActionsECRRole
          aws-region: ap-southeast-2

      - name: Test AWS
        run: |
          aws sts get-caller-identity

      # Login Docker → ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build image
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/learning-aws:${{ github.sha }} \
            -t ${{ steps.login-ecr.outputs.registry }}/learning-aws:latest .

      # Push image → ECR
      - name: Push Docker image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/learning-aws:${{ github.sha }}
          docker push ${{ steps.login-ecr.outputs.registry }}/learning-aws:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          script: |
            IMAGE="IMAGE="749203477175.dkr.ecr.ap-southeast-2.amazonaws.com/learning-aws:${{ github.sha }}"

            aws ecr get-login-password --region ap-southeast-2 | \
              docker login \
                --username AWS \
                --password-stdin \
                749203477175.dkr.ecr.ap-southeast-2.amazonaws.com

            docker pull "$IMAGE"

            docker stop hello-learning-aws || true
            docker rm hello-learning-aws || true

            docker run -d \
              --name hello-learning-aws \
              -p 3000:3000 \
              "$IMAGE"

            docker ps