name: GHCR Test

on:
  workflow_dispatch:

jobs:
  test-ghcr:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to EC2 and pull image
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ghcr.io/hoangth89/aws:latest